PROJECT = quadr
SRC_FILES= \
	main.c \
	Makefile \
	quadr.c \
	quadr.h \
	README \
	test.data

CFLAGS = -g -Wall -std=c11
LDFLAGS = -lm
quadr:	quadr.o main.o
	$(CC) quadr.o main.o -o  $@ $(LDFLAGS)
dist: $(PROJECT).tar.gz
$(PROJECT).tar.gz:		$(SRC_FILES)
	tar -cf $(PROJECT).tar $(SRC_FILES)
	gzip -f $(PROJECT).tar
main.o: main.c quadr.h
quadr.o: quadr.c quadr.h

clean:
		rm -f *.o $(PROJECT) $(PROJECT).tar.gz
depend:
		$(CC) -MM $(CPPFLAGS) *.c

